services:
    settings-web:
        build: .
        ports:
            - "3000:3000"
        environment:
            - DB=${DB}
            - KEY_1=${KEY_1}
            - KEY_2=${KEY_2}
            - KEY_3=${KEY_3}
